_.ambient.rootmodule("base/")
    .include("base")
    .include("basicstring")
    .include("basicpath")
    .include("basicmath")
    .include("basicdate")
    .include("basicarray")
    .include("basicjson")
